class Observation(object):
    """ MATK observation class
    """
    def __init__(self, name, **kwargs):
        self._name = name
        self._value = None
        self._sim = None
        self._residual = None
        self._weight = 1.0
        for k,v in kwargs.iteritems():
            if k == 'weight':
                self._weight = v
            elif k == 'value':
                self._value = v
            elif k == 'sim':
                self._sim = v
            else:
                print k + ' is not a valid argument'
    @property
    def name(self):
        '''Observation name'''
        return self._name
    @name.setter
    def name(self,value):
        self._name = value
    @property
    def value(self):
        '''Observation value'''
        return self._value
    @value.setter
    def value(self,value):
        self._value = value
    @property
    def weight(self):
        '''Weight to apply to simulated values'''
        return self._weight
    @weight.setter
    def weight(self,value):
        self._weight = value
    @property
    def sim(self):
        '''Simulated value generated by MATK model'''
        return self._sim
    @sim.setter
    def sim(self,value):
        if value is not None:
            self._sim = value
        else:
            self._sim = None
    @property
    def residual(self):
        '''Observation value minus simulated value'''
        self._residual = (self._value - self._sim) / self._weight
        return self._residual
    @residual.setter
    def residual(self,value):
        self._residual = value
